Settings:
  ServerName: lobby # Used to identify the server in a BungeeCord network
  Language: en_EN
  Updates:
    DisableNotifications: false
    CheckForDevBuilds: true
    Notify:
      Console: true
      InGame: true
  Debug: false

MySQL:
  Host: 127.0.0.1
  Port: 3306
  Database: database
  Username: username
  Password: password
  TablePrefix: tc_
  JDBCArgs: sslMode=true

# Here you can customize destination-types
# At this time it is not possible to use whitespaces in displayNames

DestinationTypeAll:
  DisplayName: All
  DisplayNameColor: yellow

DestinationTypes:
  - Name: STATION
    DisplayName: Station
    DisplayNameColor: yellow
    ShowOwnerInformations: false
    DynmapIcon: rail.png

  - Name: MAIN_STATION
    DisplayName: Main-Station
    DisplayNameColor: yellow
    ShowOwnerInformations: false
    DynmapIcon: rail.png

  - Name: PUBLIC_STATION
    DisplayName: Public
    DisplayNameColor: yellow
    ShowOwnerInformations: true
    DynmapIcon: rail.png

  - Name: PLAYER_STATION
    DisplayName: Player-Station
    DisplayNameColor: gold
    ShowOwnerInformations: true
    DynmapIcon: minecart.png