Settings:
  ServerName: lobby
  Debug: false
  Updates:
    DisableNotifications: false
    CheckForDevBuilds: true
    Notify:
      Console: true
      InGame: true

MySQL:
  Host: 127.0.0.1
  Port: 3306
  Database: database
  Username: username
  Password: password
  TablePrefix: tc_

DestinationTypeAll:
  DisplayName: All
  DisplayNameColor: yellow

DestinationTypes:
  - Name: station
    DisplayName: Station
    DisplayNameColor: yellow
    ShowOwnerInformations: false
    DynmapIcon: rail.png

  - Name: main_station
    DisplayName: Main-Station
    DisplayNameColor: yellow
    ShowOwnerInformations: false
    DynmapIcon: rail.png

  - Name: public_station
    DisplayName: Public
    DisplayNameColor: yellow
    ShowOwnerInformations: true
    DynmapIcon: rail.png

  - Name: player_station
    DisplayName: Player-Station
    DisplayNameColor: gold
    ShowOwnerInformations: true
    DynmapIcon: minecart.png