name: TCDestinations
version: 1.0-BETA4
build: NO-CI
main: de.crafttogether.TCDestinations
api-version: 1.21
authors: [ J0schlZ, Ceddix, StonDragonlp ]
description: TrainCarts-Addon which allows you to manage destinations in a more advanced way.
website: https://github.com/CraftTogetherMC
depend:
  - CTCommonsBukkit
  - BKCommonLib
  - Train_Carts
softdepend:
  - dynmap